/**
 * Restore original embeddings after contextual enrichment A/B test.
 *
 * 1. Reads backup from data/enrichment-backup.json
 * 2. Restores original vectors in SQLite
 * 3. Renames vectors.bin.bak → vectors.bin, vectors.meta.jsonl.bak → vectors.meta.jsonl
 * 4. Deletes backup file
 */

import { Database } from "bun:sqlite";
import { EMBEDDING_MODELS } from "../src/services/rag/embeddings.ts";

const DB_PATH = process.env.DB_PATH ?? "./data/leyabierta.db";
const DATA_DIR = process.env.VECTORS_DIR ?? "./data";
const MODEL_KEY = "gemini-embedding-2";
const _model = EMBEDDING_MODELS[MODEL_KEY]!;
const db = new Database(DB_PATH);
const fs = require("node:fs");

const backupPath = `${DATA_DIR}/enrichment-backup.json`;

// ── Step 1: Load backup ──
if (!(await Bun.file(backupPath).exists())) {
	console.error(`No backup found at ${backupPath}. Nothing to restore.`);
	process.exit(1);
}

const backupData: Array<{
	normId: string;
	blockId: string;
	vector: number[];
}> = JSON.parse(await Bun.file(backupPath).text());

console.log(`=== Restoring ${backupData.length} embeddings ===\n`);

// ── Step 2: Restore SQLite ──
const updateStmt = db.prepare(
	"UPDATE embeddings SET vector = ? WHERE norm_id = ? AND block_id = ? AND model = ?",
);

let restored = 0;
for (const b of backupData) {
	const f32 = new Float32Array(b.vector);
	const buf = Buffer.from(f32.buffer);
	updateStmt.run(buf, b.normId, b.blockId, MODEL_KEY);
	restored++;
}
console.log(`  Restored ${restored} embeddings in SQLite`);

// ── Step 3: Restore vector files ──
const vecBin = `${DATA_DIR}/vectors.bin`;
const vecMeta = `${DATA_DIR}/vectors.meta.jsonl`;

// Delete the re-exported files (generated by the enriched API)
if (fs.existsSync(vecBin)) fs.unlinkSync(vecBin);
if (fs.existsSync(vecMeta)) fs.unlinkSync(vecMeta);

// Rename .bak back
if (fs.existsSync(`${vecBin}.bak`)) {
	fs.renameSync(`${vecBin}.bak`, vecBin);
	console.log(`  ${vecBin}.bak → ${vecBin}`);
}
if (fs.existsSync(`${vecMeta}.bak`)) {
	fs.renameSync(`${vecMeta}.bak`, vecMeta);
	console.log(`  ${vecMeta}.bak → ${vecMeta}`);
}

// ── Step 4: Delete backup ──
fs.unlinkSync(backupPath);
console.log(`  Deleted ${backupPath}`);

console.log(`
=== Done ===

Original embeddings restored. Restart API to use them:
  bun run api
`);
